adding checks for docker hub and github accessiblity in case of online update

diff --git a/loginvsid b/loginvsid
--- a/loginvsid
+++ b/loginvsid
@@ -136,6 +136,12 @@ update() {
   fi
   if [ -z $offline ]; then
       if [ -z $internal ]; then        
+        curl -Lfs -m 10 https://github.com/LoginVSI/VirtualAppliance.git
+        if [[ $? != 0 ]]; then 
+          echo "Failed to connect to github.com, make sure the appliance can access github.com"
+          exit
+        fi
+
         git clone -q https://github.com/LoginVSI/VirtualAppliance.git /loginvsi/update
       else
         read -ep "InternalUrl for virtual appliance: " applianceurl
diff --git a/update b/update
--- a/update
+++ b/update
@@ -24,6 +24,16 @@ while read -r repo branch hostingfolder; do
             echo "Performing internal update from $2" 
             git clone -q -b "$branch" "$2" /loginvsi/hosting;
         else
+            curl -Lfs -m 10 https://github.com/LoginVSI/VirtualAppliance.git
+            if [[ $? != 0 ]]; then 
+                echo "Failed to connect to github.com, make sure the appliance can access github.com"
+                exit
+            fi
+            curl -Lfs -m 10 https://hub.docker.com
+            if [[ $? != 0 ]]; then 
+                echo "Failed to connect to hub.docker.com, make sure the appliance can access hub.docker.com"
+                exit
+            fi
             echo "Performing online update from $repo" 
             git clone -q -b "$branch" "$repo" /loginvsi/hosting;
         fi
