debugging

diff --git a/update b/update
--- a/update
+++ b/update
@@ -29,7 +29,7 @@ while read -r repo branch hostingfolder; do
             curl -Lfs -m 10 https://github.com/LoginVSI/VirtualAppliance.git &> /dev/null || (echo "Failed to connect to github.com, make sure the appliance can access github.com" && exit 1)
             curl -Lfs -m 10 https://hub.docker.com &> /dev/null || (echo "Failed to connect to hub.docker.com, make sure the appliance can access hub.docker.com" && exit 1)                        
             echo "Performing online update from $repo" 
-            git clone -q -b "$branch" "$repo" /loginvsi/hosting || (echo "Failed to clone repository, make sure the appliance can access github" && exit 1)                        
+            git clone -q -b "$branch" "$repo" /loginvsi/hosting || (echo "Failed to clone hosting repository, make sure the appliance can access github" && exit 1)                        
         fi
     else
         # offline updater, copy hosting files from hosting folder on iso        
